version: "3.6"

services:
 sut:
  build:
   context: ./test
   args:
    ENGINE_VERSION: ${ENGINE_VERSION:-5.5.0}
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/citygen/"
    - "./test/mod:/root/.minetest/worlds/world/worldmods/citygen_test/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"
  ports:
    - "30000:30000/udp"

volumes:
  world: {}